type SpriteSheetKeyV11 =
    "background"
    | "atlasBackground"
    | "normalActive"
    | "notableActive"
    | "keystoneActive"
    | "normalInactive"
    | "notableInactive"
    | "keystoneInactive"
    | "mastery"
    | "masteryConnected"
    | "masteryActiveSelected"
    | "masteryInactive"
    | "masteryActiveEffect"
    | "masteryOverlay"
    | "ascendancyBackground"
    | "ascendancy"
    | "startNode"
    | "groupBackground"
    | "frame"
    | "jewel"
    | "line"
    | "jewelRadius";