name: Deploy Website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Build
      uses: ./.github/actions/build

    - name: Add Scripts
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "<!-- %SCRIPT_REPLACE_MARKER% -->"
        replace: ${{ secrets.SCRIPTS }}
        regex: false
        include: dist/index.html

    - name: Publish
      uses: easingthemes/ssh-deploy@main
      env:
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SOURCE: "dist/"
        TARGET: ${{ secrets.SSH_DIR }}
